name: iOS Smoke Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test using Xcode
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Run UI Tests
        # Замініть 'CodeBreaker' на назву вашого Scheme в Xcode
        # platform=iOS Simulator,name=iPhone 15 - вказує на якому пристрої тестувати
        run: |
          xcodebuild test \
            -scheme "CodeBreaker" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -enableCodeCoverage YES \
            clean test
