name: MobSF Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run MobSF Analysis
        run: |
          echo "Pulling MobSF image..."
          docker pull opensecurity/mobile-security-framework-mobsf:latest
          
          echo "Running Scan..."
          docker run --rm \
            -v ${{ github.workspace }}:/home/mobsf/source \
            opensecurity/mobile-security-framework-mobsf:latest \
            /bin/bash -c "source venv/bin/activate && python3 manage.py scan --src /home/mobsf/source --output /home/mobsf/source/report.json --format json"

      - name: Upload MobSF Report
        uses: actions/upload-artifact@v4
        with:
          name: Security-Report-MobSF
          path: report.json
